### PR TITLE
Adds a utility method to ViewUtils to prevent multi click

### LINKED ISSUE #147: Item can be opened twice
Double click on one item opens it twice
[video](https://dl2.pushbulletusercontent.com/RlmtcHTqGsVSMN0UE8oD7DlnMC3nZ00Q/plaid_bug.mp4)

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Closes #147

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
I signed it!

**Comment by shobhitagarwal1612** [comment]
@nickbutcher I also tried creating a Kotlin extension function but was unable to call it from the `FeedAdapter`.

**Comment by shobhitagarwal1612** [comment]
@nickbutcher Please review

**Comment by amilcar-andrade** [comment]
It seems this is an edge case. Why would you always wait for 500 ms every time?

**Comment by amilcar-andrade** [comment]
Also, from the comments from Nick you would probably want to do it using ButterKnife

**Comment by shobhitagarwal1612** [comment]
Thanks. I'll update the PR

**Comment by nickbutcher** [comment]
Thank you for the PR but this is not something we'd like to merge in the project. In the future please feel free to open an issue prior to developing a feature to discuss.

**Pull request closed without merging**
