### PR TITLE
FileProvider: Create files authority inside build.gradle

### PR DESCRIPTION
**Pull request by amilcar-andrade**
@nickbutcher please review and merge if you think these are good changes.

### CODE REVIEW

**Comment by nickbutcher** [comment]
Thanks for the PR! I like the authority trick but don't see the advantage of the WekRef. You're never checking if `get()` returns null so this is liable to break. Could you resubmit with just 299dfdd?

**Comment by amilcar-andrade** [comment]
Sure 👍

**Comment by amilcar-andrade** [comment]
@nickbutcher done!

**Comment by nickbutcher** [comment]
Thanks! cc/ @ianhanniballake

**Pull request merged**
