### PR TITLE
[DO NOT MERGE] Bump versionName to 1.0.8 for release.

### PR DESCRIPTION
**Pull request by tiembo**
Also bump AGP to 3.4.0-alpha07.

### CODE REVIEW

**Comment by tiembo** [comment]
Merge after 1.0.8 is fully rolled out.

**Comment by florina-muntenescu** [comment]
@tiembo - What's the status here? Could we merge this?

**Comment by ataulm** [comment]
>Merge after 1.0.8 is fully rolled out.

I see 1.0.7 in the Play Store (updated 14 Nov) but on the web Play Store I see last update was 10 December 🤔

**Comment by tiembo** [comment]
1.0.8 was rolled out to internal testers only.  We ran into some issues and decided to postpone the 1.0.8 general rollout.

Closing this PR - will open another one when we're ready for another 1.0.8 release :ship:

**Pull request closed without merging**
