### PR TITLE
Ferini/kotlin gradle dsl

### PR DESCRIPTION
**Pull request by ferinagy**
## :loudspeaker: Type of change

- [ ] Bugfix
- [ ] New feature
- [x] Enhancement
- [x] Refactoring

## :pencil: Checklist

- [ ] I ran `./gradlew spotlessApply` before submitting the PR
- [ ] I reviewed submitted code
- [ ] I added tests to verify changes
- [ ] All tests passing

### CODE REVIEW

**Comment by keyboardsurfer** [comment]
Hi, thanks for the PR. How is this different to #807?

**Comment by ghus-raba** [comment]
> Hi, thanks for the PR. How is this different to #807?

Hi, I did this as part of experimenting with kotlin DSL on a separate branch and wanted a way to share the diff of what was done. It was not intended to be merged in this state, that's why it is only draft. In the hindsight, I probably could just create a PR in my forked repo.

I saw the other one already exists and it is mostly similar to this one. I took some different approach in some areas (eg. I kept separate shared_dependencies.gradle.kts and test_dependencies.gradle.kts and moved them to buildSrc as precompiled plugins), but I am not sure if that makes this one better suitable than the other. 

If you want to check it out and think this might be better candidate to merge, I am happy to clean it up, otherwise feel free to close it.

**Comment by keyboardsurfer** [comment]
@pfmaggi FYI

**Comment by pfmaggi** [comment]
As @ghus-raba wrote, the main difference is having the precompiled plugins for the dependencies while #807 keep them together in a module.

Most of the other things seems small differences.
#807 is still using AGP 3.6 as there's an issue with 4.0 when running the tests.

**Comment by pfmaggi** [comment]
Thanks @ghus-raba for the PR, I'm updating #807 using some of the ideas you used here.

**Pull request closed without merging**
