### PR TITLE
Backport pt. II (finished?)

### PR DESCRIPTION
**Pull request by hzsweers**
This is a mostly complete backport of the remaining portions of the app. At this point, future bugs would have to be found by using the app in the wild and fixing them on the fly.

No real structure to this one other than just trying to use the app on an older device and seeing what breaks.

Notable changes and decisions:
- Introduction of Transitions-Everywhere library for some transition backporting
  - Transitions that aren't backward compatible (namely shared element transitions) have been gated off
- More xml drawable separation between pre and post-21 (namely ripples, avds, and animated-selector)
  - In particular, some avds have paths that aren't backward compatible
  - animated-selector has no backporting, so separation consists entirely of just having a pre-21 selector that has no animations
- Backward compatible CircularImageView implementation for avatars
- Used real FloatingActionButtons where appropriate for pre-21 shadow/elevation support
- Left styles mixing pre and post API 21 attributes because ultimately it doesn't care if they're mixed (despite lint making it appear otherwise). For me, this was cleaner since most of the new attributes were just supplementary and didn't actually change the UI's structure or behavior that much.

Notable issues:
- Draggable FrameLayout doesn't work pre-21 if you don't use something that natively implements nested scrolling
- Due to FrameLayout ordering, HomeActivity's toolbar is always on top pre-lollipop due to not being able to take advantage of elevations.
- BottomSheet shown from trying to post something to DN doesn't animate nicely. Dunno what the right approach for this is.

I've tested this pretty thoroughly, and I think it's ready.

### CODE REVIEW

**Comment by ansumanshah** [comment]
will this be merged?

**Comment by SUPERCILEX** [comment]
Merge status?

**Comment by hzsweers** [comment]
I don't think it's going to happen. This was a fun exercise in using the support libraries and learning more about what goes into backporting APIs, but ultimately Lollipop is nearly 90% in my personal projects and only climbing, so I don't think this is worth pursuing :).

**Comment by SUPERCILEX** [comment]
Cool beans!

**Comment by nickbutcher** [comment]
Sorry for lack of comments here on this… think I was a little overwhelmed with this PR!

With the ecosystem getting nearer to `minSdk=21` being realistic, I don't think that Plaid should have (and maintain) an 'official' backport branch. As such I don't think that this will be merged; BUT i'd like to be able to point people to this fork if they are interested in backward compat.

I'll update the `README` to be more explicit on the project's goals and link to @hzsweers' fork. I'll also remove my `backport` branch.

Sound good?

**Comment by hzsweers** [comment]
Sure! Though note that I'm not actively working on it or keeping it up to date

**Pull request closed without merging**
