### PR TITLE
Migrate getAuthedUser to use Designer News V2 API

### PR DESCRIPTION
**Pull request by amilcar-andrade**

### CODE REVIEW

**Comment by amilcar-andrade** [comment]
@nickbutcher it seems the V1 API is not longer working. See https://www.designernews.co/api/v1/me
 
I changed `getAuthedUser` to use v2. I can work on other rest end points if you are OK with that. Let me know. Thanks!

**Comment by amilcar-andrade** [comment]
@nickbutcher maybe I should remove the 2nd commit. Now I can see the stories but if I click on them I get a lot of crashes because some of the fields are not longer there or the API changed. I am going to stop working on this. Let me know what do u think. Thanks!

**Comment by nickbutcher** [comment]
Thanks for another solid contribution! I've just started work migrating to v2 of the Designer News API. I'll push up a new branch soon and maybe PR that rather than pushing this into master. Follow #175 for updates.

**Comment by amilcar-andrade** [comment]
@nickbutcher Oh sorry I totally missed issue [175](https://github.com/nickbutcher/plaid/issues/175)
Anyway, feel free to grab my commits also I am down to help if you want me to.

**Comment by nickbutcher** [comment]
Thank you for the contribution but we're currently working on a larger change to Plaid (see README) including updating to the DN v2 API so will close this PR.

**Pull request closed without merging**
