### PR TITLE
Fixes NPE when response body is null and adds visual indicator

### PR DESCRIPTION
**Pull request by amilcar-andrade**
- Fixes NPE when the dribble login response body is null
- Replaces Toast for a TextView

### CODE REVIEW

**Comment by amilcar-andrade** [comment]
@nickbutcher could you please review? While creating my dribble credentials I realized you can get a NPE when reading the response body also I changed the Toast for a SnackBar.

Thanks!

**Comment by nickbutcher** [comment]
Thanks but not sure how a snackbar works with a dialog, could you upload a quick screen–record of this change? Thanks!

**Comment by amilcar-andrade** [comment]
@nickbutcher I changed to use the SnackBar because of the `TODO` in line 156.  Attached are some videos showing the behavior using a SnackBa, Toast and showing the old behavior. Let me know which one you want to be using.

*TOAST*
toast

*SNACK*
snack

*CRASH*
crash_dribblbe

**Comment by Jawnnypoo** [comment]
I prefer the crash one :P

**Comment by nickbutcher** [comment]
Hmm, none of those are wonderful, especially the crash!! What about adding a TextView in the dialog below the login button reporting the failure (prob using @color/error). It could remain until you click the button again.

What do you think?

**Comment by amilcar-andrade** [comment]
Sure, I can do that. I will post a video. Thanks!

**Comment by amilcar-andrade** [comment]
@nickbutcher check it out...
textview

**Comment by nickbutcher** [comment]
Looks great, thanks for the changes!

**Pull request merged**
