### PR TITLE
Prevent PlayerActivity from crashing

### PR DESCRIPTION
**Pull request by amilcar-andrade**

### CODE REVIEW

**Comment by amilcar-andrade** [comment]
I signed it!

**Comment by nickbutcher** [comment]
Sorry for the slow review – thanks for the contribution!

**Comment by amilcar-andrade** [comment]
@nickbutcher no worries, I am sure you were busy working on the new Google I/O app (by the way looks cool). 

Also I have two questions, I cannot login to my dribble or designer news account when I am using the development branch/build , but If I downloaded the app from the app store and I able to do it, Do you know how can I use my accounts when developing? 

And the second one, is that if you have some other enhancements, ideas or bugs. I would want to help with those, I really like the app it is pretty nice and it shows a lot of design ideas that like and I am trying to learn.

Thanks in advance!

**Comment by nickbutcher** [comment]
You likely can't log in with your build as you need to supply your own API keys in `gradle.properties` for that to work. The release build on the Play Store is built with my keys.

Thanks for offering to contribute! Two ideas of things I know need work:

- Better landscape / tablet layouts
- Data persistance!

Would love contributions in that area. Otherwise there are a few outstanding issues; it would be amazing if you wanted to look in to any of them?

**Comment by amilcar-andrade** [comment]
@nickbutcher Oh that makes sense!

Yeah I will be down to work on better landscape/tablet layouts just let me know what screen do you think it is the best one, also I can help with the some issues so I can learn other parts of the app.

**Comment by nickbutcher** [comment]
The `DribbbleShot` screen in particular is bad on tablets/landscape. Might be a good place to start. Thanks again!

**Comment by amilcar-andrade** [comment]
@nickbutcher I sent you a message [yesterday](https://plus.google.com/114154139513868803303/posts/EwiKEwPVgQY), let me know if you have some other ideas about the landscape views. Thanks!

**Pull request merged**
