### PR TITLE
Improve legibility of TextViews

### PR DESCRIPTION
**Pull request by anddev-badvice**
screenshot_1502456090

### CODE REVIEW

**Comment by nickbutcher** [comment]
GTFO.

**Comment by romannurik** [comment]
+1 to OP plz reopen I need this

**Comment by safaorhan** [comment]
We were waiting for this feature. Please reopen this issue to discussion.

**Comment by hzsweers** [comment]
even CLA bot isn't having it

**Comment by Saketme** [comment]
Nick is literally hitler.

**Pull request closed without merging**
