### PR TITLE
Reduced launcher icon size

### PR DESCRIPTION
**Pull request by konifar**
`ic_launcher` icons were not optimized.
So I optimized icons by using [ImageOptim](https://imageoptim.com/).

After optimized, the icons size reduced 21.3% on average.

imageoptim

### CODE REVIEW

**Comment by konifar** [comment]
@googlebot I signed it!

**Comment by nickbutcher** [comment]
Awesome, thanks! cc/ @romannurik

**Comment by romannurik** [comment]
Sweet! I think the build tools do some optimization as well but good to be tidy!

**Comment by konifar** [comment]
Thanks for merge!

**Pull request merged**
