### PR TITLE
Code simplified

### PR DESCRIPTION
**Pull request by XinyueZ**

### CODE REVIEW

**Comment by XinyueZ** [comment]
why  "Your tests failed on CircleCI" -> 

```
#!/bin/bash -eo pipefail
scripts/ftl_setup.sh
GCLOUD_SERVICE_KEY env variable is empty. Exiting.
Exited with code 1
```

This change is only one line simplify. 😢

**Comment by tiembo** [comment]
@XinyueZ we just turned the feature for building forked PRs and are tweaking the settings.  Apologies for the false test failure.

**Comment by tiembo** [comment]
Hi @XinyueZ can you pull in the latest code? There are some CI changes that should fix forked CI builds.  Thank you!

**Comment by XinyueZ** [comment]
I abolish this PR for some problems of the relocation of my working computer, something goes wrong.

**Pull request closed without merging**
